Neos:
  Flow:
    mvc:
      routes:
        # Override this to false to not add the SEO routes.
        'Neos.Seo':
          variables:
            # Override this to change the uri to the sitemap
            xmlSitemapPath: 'sitemap.xml'
  Neos:
    fusion:
      autoInclude:
        'Neos.Seo': true

    userInterface:
      translation:
        autoInclude:
          'Neos.Seo': ['NodeTypes/*']

  Fusion:
    defaultContext:
      'Neos.Seo.Image': 'Neos\Seo\Fusion\Helper\ImageHelper'

  Seo:
    # hreflang settings
    alternateLanguageLinks:
      excludedDimensionsPresets: []
    # robots.txt settings
    robotsTxt:
      dimensionsPresets: null
      excludedDimensionsPresets: []
    # Facebook settings
    facebook:
      # The id of the user that can be followed on this site
      profileId: ''
      # List of facebook user ids of your pages/apps administrators
      admins: []
      # List of facebook channel ids of your pages
      pages: []
    # Social profile for the structured data object
    socialProfile:
      # `type` can be either `Person` or `Organization`
      type: 'Organization'
      # `logo` can be for example `resource://Vendor.Site/Public/Images/MyLogo.png`
      logo: ''
      profiles:
        facebook: ''
        instagram: ''
        linkedIn: ''
        youTube: ''

  Media:
    thumbnailPresets:
      # Presets based on https://developers.facebook.com/docs/sharing/best-practices#images
      'Neos.Seo:OpenGraph.Square':
        maximumWidth: 1080
        maximumHeight: 1080
      'Neos.Seo:OpenGraph.Landscape':
        maximumWidth: 1200
        maximumHeight: 628

